name: ESLint

on: pull_request

jobs:
  lint_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/actions-yarn@v2.0.0
        with:
          node-version: 12
      - run: yarn ci
      - run: yarn run install:all
      - run: yarn run lint
